Presentation/BBH.Lotte.Web/Controllers/CaptchaController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BBH.Lotte.Web.Controllers
{
    public class CaptchaController : Controller
    {
        // GET: Captcha
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SubmitCapcha()
        {
            var response = Request["g-recaptcha-response"];
            string secretKey = "6LfhJyUUAAAAAPKM6Hl87lD0mVKa-0zPKNR53W_j";
            var client = new WebClient();
            var result = client.DownloadString(string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secretKey, response));
            var obj = JObject.Parse(result);
            var status = (bool)obj.SelectToken("success");
            if (status == true)
            {
                ViewBag.Message = "Your Google reCaptcha validation success";
            }
            else
            {
                ViewBag.Message = "Your Google reCaptcha validation failed";
            }
            Session["CaptchaCode"] = response;

            return View("SubmitCapcha");
        }
    }
}

Presentation/BBH.Lotte.Web/Views/Captcha/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Index</h2>
<div class="fairform">
    @using (Html.BeginForm("SubmitCapcha", "Captcha", FormMethod.Post))
    {
        <form action="#" method="POST" id="checkfair" onsubmit="return false;">
            <h2>I want to check the result</h2>
            <div class="small_switcher">
                <div class="smsw_switcher">
                    <!--span data-switchervalue="old" class="">1 - 113 draws</span-->
                    <!--span class="onsw new_active"></span-->
                    @*<span data-switchervalue="new" class="active">114 and newer</span>*@
                </div>
            </div>
            <div class="box-field">
                <label class="box-field__label" for="bhash">Block Hash <span style="color:red">*</span></label>
                <div class="box-field__input">
                    <input type="text" id="bhash" name="btchash" autocomplete="off" class="input-text" placeholder="" style="color:#000">
                </div>
                <p class="help-block" id="spanlockhash" style="display:none; color:Red"> </p>
                @*<div class="box-field-subtext">Hash of any circulation can be found in <a href="/info/archive" target="_blank">the archive</a></div>*@
            </div>

            @*<div class="g-recaptcha" id="rccheck" data-size="normal" >


                            <label for="capcha">Security code <span style="color:red">*</span></label>
                    <div style="float:left;width:100%">
                        <div style="float:left;width:50%">
                            <input id="txtCatpcha" name="txtCatpcha" onfocus="ResetCaptcha()" class="form-control">
                        </div>
                        <div style="float:right;width:50%">
                            <img class="img-responsive" style="margin-left: 10px;height: 40px;margin-top: 4px;" src="/AjaxHandler/WriteImageCaptchaCheckResultLotte.aspx" id="imgCaptchaSignup">
                            <a href="javascript:void(0)" class="btn-reload" onclick="RefreshCaptchaCheckResult()"><img src="/images/reload.png"></a>
                        </div>

                    </div>
                    <p class="help-block" id="spanCatcha" style="display:none; color:Red"> </p>



                @*<div style="width: 304px; height: 78px;"><div><iframe src="https://www.google.com/recaptcha/api2/anchor?k=6LfqiBsUAAAAAAW0UOWA5YFptRFh7p9gpwOk2SOe&amp;co=aHR0cHM6Ly90cnVlZmxpcC5pbzo0NDM.&amp;hl=vi&amp;v=r20171031153338&amp;theme=light&amp;size=normal&amp;cb=alrp9tuim6kp" width="304" height="78" role="presentation" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"></iframe></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;  display: none; "></textarea></div>

                </div>*@

            <div class="g-recaptcha" id="captcha" data-sitekey="@(System.Configuration.ConfigurationManager.AppSettings[BBH.Lotte.Shared.KeyManager._SITE_KEY_CAPTCHA])"></div>
            <span style="display:inline-block; font-size:20px;margin:20px 0;padding:20px;border:1px solid #D3D3D3" id="ErrCaptcha">
                @ViewBag.Message
            </span>

            @*<input type="hidden" value="1" name="new" id="checkerNew">*@
            <input type="submit" onclick="CheckResultNumber()" class="btn-orange btn-short" value="Check">
        </form>
    }
</div>